# Stage 1: Build the Vue.js application
FROM node:14 AS build

# Set the working directory in the Docker image
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the project files into the Docker image
COPY . .

# Build the application
RUN npm run build

# Stage 2: Serve the application using Nginx
FROM nginx:stable-alpine

# Copy the built assets from the build stage
COPY --from=build /app/dist /usr/share/nginx/html

# Copy the default nginx.conf provided by tiangolo/node-frontend
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy the script that will start Nginx and replace environment variables
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Copy the config template
COPY config.js /usr/share/nginx/html/config.js

EXPOSE 80

# Start Nginx server and replace environment variables
CMD ["/entrypoint.sh"]
